# version: '3.8'

services:
  # Core API Server
  flint-core:
    build:
      context: ./flint-core
      dockerfile: Dockerfile
      target: development  # Specify the development stage
    volumes:
      - ./flint-core/src:/app/src
      - ./flint-core/package.json:/app/package.json  # Mount package.json
      - ./flint-core/package-lock.json:/app/package-lock.json  # Mount package-lock.json
      - ./flint-core/nodemon.json:/app/nodemon.json  # Ensure nodemon settings are applied
      - ./flint-core/.env:/app/.env
    env_file:
      - ./flint-core/.env # need to load .env.dev
    environment:
      - NODE_ENV=development
      - DB_HOST=flint-db       # Set DB_HOST directly in docker-compose

  # AI & Scripting Service
  flint-worker:
    build:
      context: ./flint-worker
      dockerfile: Dockerfile
      target: development  # Specify the development stage
    volumes:
      - ./flint-worker/src:/app/src
      - ./flint-core/package.json:/app/package.json  # Mount package.json
      - ./flint-core/package-lock.json:/app/package-lock.json  # Mount package-lock.json
      - ./flint-core/nodemon.json:/app/nodemon.json  # Ensure nodemon settings are applied
      - ./flint-core/.env:/app/.env
    env_file:
      - ./flint-worker/.env # need to load .env.dev²
    environment:
      - NODE_ENV=development

  # React Frontend
  flint-face:
    build:
      context: ./flint-face
      dockerfile: Dockerfile
      target: development  # Specify the development stage
    volumes:
      - ./flint-face/src:/app/src
      - ./flint-face/public:/app/public
      - ./flint-face/package.json:/app/package.json
      - ./flint-face/package-lock.json:/app/package-lock.json
      - ./flint-face/.env:/app/.env # Mount .env file for development
    env_file:
      - ./flint-face/.env # need to load .env.dev
    environment:
      - NODE_ENV=development
      - VITE_ENV=development